name: Build Docker images
on:
  push:
  pull_request:
  schedule:
    - cron: '15 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { MAJOR_VERSION: "6", MINOR_VERSION: "8", PATCH_VERSION: "23" }
          - { MAJOR_VERSION: "7", MINOR_VERSION: "17", PATCH_VERSION: "29" }
          - { MAJOR_VERSION: "8", MINOR_VERSION: "17", PATCH_VERSION: "8" }
          - { MAJOR_VERSION: "8", MINOR_VERSION: "18", PATCH_VERSION: "3" }
    steps:
      - uses: actions/checkout@v4

      # Optional but recommended: load QEMU for cross‑arch emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
          
      - name: "Set up Docker Buildx"
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: "Build & tag image (optionally push)"
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64
          tags: |
            rikwillems/elasticsuite-elasticsearch:${{ matrix.cfg.MAJOR_VERSION }}.${{ matrix.cfg.MINOR_VERSION }}.${{ matrix.cfg.PATCH_VERSION }}
            rikwillems/elasticsuite-elasticsearch:${{ matrix.cfg.MAJOR_VERSION }}.${{ matrix.cfg.MINOR_VERSION }}-latest
            rikwillems/elasticsuite-elasticsearch:${{ matrix.cfg.MAJOR_VERSION }}-latest
          build-args: |
            MAJOR_VERSION=${{ matrix.cfg.MAJOR_VERSION }}
            MINOR_VERSION=${{ matrix.cfg.MINOR_VERSION }}
            PATCH_VERSION=${{ matrix.cfg.PATCH_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' }}
