name: Build Docker images
on:
  push:
  pull_request:
  schedule:
    - cron: '15 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { ELASTICSEARCH_VERSION: "7.17.29" }
          - { ELASTICSEARCH_VERSION: "8.17.8" }
          - { ELASTICSEARCH_VERSION: "8.18.3" }
    steps:
      - uses: actions/checkout@v4
      
      - name: "Build Docker image"
        run:
          docker build .
          --tag rikwillems/docker-elasticsuite-elasticsearch:${{ matrix.cfg.ELASTICSEARCH_VERSION }}
          --platform linux/amd64,linux/arm64
          --build-arg ELASTICSEARCH_VERSION=${{ matrix.cfg.ELASTICSEARCH_VERSION }}

      - name: "Docker Hub - Login"
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: "Docker Hub - Push"
        if: github.ref == 'refs/heads/main'
        run: docker push rikwillems/docker-elasticsuite-elasticsearch:${{ matrix.cfg.ELASTICSEARCH_VERSION }}
